export const userName = state => { return state.userName }
export const identify = state => { return state.identify }
export const player = state => { return state.player }
export const gameStart = state => { return state.gameStart }
export const online = state => { return state.userName.length }
export const night = state => { return state.night }
export const nightCount = state => { return state.nightCount }
export const step = state => { return state.step }
export const vote = state => { return state.vote }
export const killed = state => { return state.killed }
