export const SET_USERNAME = 'SET_USERNAME'
export const SET_IDENTIFY = 'SET_IDENTIFY'
export const SET_NIGHT = 'SET_NIGHT'
export const SET_STEP = 'SET_STEP'
export const SET_GAMEOVER = 'SET_GAMEOVER'
